import { Router } from "express";
import { GetAllRentals } from "../../controllers/rental/get.js";
import { CreateRental, ReturnRental } from "../../controllers/rental/post.js";
import { DeleteRental } from "../../controllers/rental/delete.js";
const RentalRoutes = Router();
RentalRoutes.get("/rentals", GetAllRentals);
RentalRoutes.post('/rentals', CreateRental);
RentalRoutes.post('/rentals/:id/return',ReturnRental);
RentalRoutes.delete('/rentals/:id', DeleteRental);
export default RentalRoutes;